name: Create Production Pull Request

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  git-production-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set current version
        id: git-tag
        run: |
          echo "current=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Create a release pull request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: staging
          GIT_PR_RELEASE_LABELS: Release
          GIT_PR_RELEASE_TEMPLATE: .github/pr-templates/.git-production-template.erb
          VERSION: ${{ git-tag.current }}
        run: |
          gem install -N git-pr-release
          git-pr-release
