name: Delete Merged Main Branches

on:
  push:
    branches:
      - '*'
    types:
      - closed

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Delete Branches
      run: |
        echo 'runed'
